# Configuration for Fraud Detection Pipeline

# Data paths
data:
  # raw_path: "data/raw/financial_fraud_detection_dataset.csv"
  # raw_path: "data/raw/sample_dataset_small.csv"
  raw_path: "data/raw/balanced_dataset.csv"
  processed_path: "data/processed/transactions.parquet"
  test_path: "data/processed/test_data.parquet"  # Will be created during data processing

# Model configurations
models:
  output_dir: "results/models"
  
  # Classification model parameters
  classification:
    hidden_layers: [256, 128, 64, 32]  # Deeper network for better feature learning
    dropout_rate: 0.5                   # Increased dropout to reduce overfitting
    batch_size: 128                     # Smaller batch size for better generalization
    epochs: 10                          # More epochs for better convergence
    l2_regularization: 0.001            # L2 regularization to prevent overfitting
  
  # Advanced sampling parameters
  sampling:
    technique: "none"                  # Disabled sampling since dataset is already manually balanced (33% fraud)
    ratio: 0.5                          # Preserved but not used when technique is none
    k_neighbors: 7                      # Preserved but not used when technique is none
  
  # Custom loss function parameters
  loss_function:
    name: "asymmetric_focal"            # Better for highly imbalanced datasets
    focal_gamma: 4.0                    # Higher gamma to focus more on hard examples
    focal_alpha: 0.3                    # Adjusted alpha for better class balance
    class_weight_ratio: 5.0             # Reduced to prevent extreme bias
  
  # Autoencoder model parameters
  autoencoder:
    hidden_layers: [128, 64, 32]        # Deeper network for better feature learning
    encoding_dim: 24                    # Larger encoding dimension to capture more patterns
    batch_size: 128                     # Smaller batch size for better generalization
    epochs: 10                          # More epochs for better convergence
    l2_regularization: 0.001            # L2 regularization to prevent overfitting

# Evaluation configurations
evaluation:
  output_dir: "results"
  threshold: null                       # Will be determined automatically
  percentile: 90                        # Lower percentile to catch more fraud cases

# MLflow configurations
mlflow:
  experiment_name: "Fraud_Detection_Experiment"
  tracking_uri: "http://localhost:5000"
  
# Spark configurations
spark:
  app_name: "FraudDetectionPipeline"
  driver_memory: "18g"  # Optimized for Apple M2 with 24GB RAM
  executor_memory: "18g"  # Optimized for Apple M2 with 24GB RAM
  max_result_size: "4g"
  num_partitions: 32  # Optimized for Apple M2 8-core CPU
  compression: "snappy"  # Use Snappy compression for better performance
