# Configuration for Fraud Detection Pipeline

# Data paths
data:
  # raw_path: "data/raw/financial_fraud_detection_dataset.csv"
  # raw_path: "data/raw/sample_dataset_small.csv"
  raw_path: "data/raw/balanced_dataset.csv"
  processed_path: "data/processed/transactions.parquet"
  test_path: "data/processed/test_data.parquet"  # Will be created during data processing

# Model configurations
models:
  output_dir: "results/models"
  
  # Classification model parameters
  classification:
    hidden_layers: [256, 128, 64]      # Slightly shallower to reduce overfitting
    dropout_rate: 0.4                    # Increased to combat overfitting
    batch_size: 256                      # Larger batch size for more stable training
    epochs: 20                           # More training time for better convergence
    l2_regularization: 0.001             # Increased regularization to prevent overfitting
  
  # Advanced sampling parameters
  sampling:
    technique: "none"                   # Temporarily disable synthetic sampling 
    ratio: 0.5                          # Default value when sampling is re-enabled
    k_neighbors: 5                      # Keep the reduced value for future use
  
  # Custom loss function parameters
  loss_function:
    name: "asymmetric_focal"           # Using asymmetric focal loss for class imbalance
    focal_gamma: 2.5                    # Increased to focus more on hard examples
    focal_alpha: 0.35                   # Slightly reduced to balance precision/recall
    class_weight_ratio: 2.5             # Reduced to improve precision
  
  # Autoencoder model parameters
  autoencoder:
    hidden_layers: [256, 128, 64]        # Deeper initial layers for better feature learning
    encoding_dim: 24                    # Increased for better representation
    batch_size: 128                     # Keep current batch size
    epochs: 20                          # More training time for better convergence
    l2_regularization: 0.0005           # Slightly reduced for better learning

# Evaluation configurations
evaluation:
  output_dir: "results"
  threshold: null                       # Will be determined automatically
  percentile: 92                        # Increased to reduce false positives

# MLflow configurations
mlflow:
  experiment_name: "Fraud_Detection_Experiment"
  tracking_uri: "http://localhost:5000"
  
# Spark configurations
spark:
  app_name: "FraudDetectionPipeline"
  driver_memory: "18g"  # Optimized for Apple M2 with 24GB RAM
  executor_memory: "18g"  # Optimized for Apple M2 with 24GB RAM
  max_result_size: "4g"
  num_partitions: 32  # Optimized for Apple M2 8-core CPU
  compression: "snappy"  # Use Snappy compression for better performance
