version: '3.8'

services:
  # MLflow tracking server
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5001:5000"
    volumes:
      - ./mlruns:/mlruns
    environment:
      - MLFLOW_TRACKING_URI=http://localhost:5001
    command: mlflow server --host 0.0.0.0 --port 5000
    # Healthcheck disabled temporarily
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:5000"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 3
    #   start_period: 30s

  # Fraud detection pipeline
  fraud-detection:
    build: .
    depends_on:
      mlflow:
        condition: service_healthy
    volumes:
      - ./:/app
      - ./data:/app/data
      - ./results:/app/results
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5001
      - CONFIG_PATH=/app/config.production.yaml
    command: python src/pipeline.py

  # Streaming fraud detection
  streaming:
    build: .
    depends_on:
      mlflow:
        condition: service_healthy
    volumes:
      - ./:/app
      - ./data:/app/data
      - ./results:/app/results
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5001
      - CONFIG_PATH=/app/config.production.yaml
    command: python src/spark_jobs/streaming_fraud_detection.py

  # Model monitoring service
  monitoring:
    build: .
    depends_on:
      mlflow:
        condition: service_healthy
    volumes:
      - ./:/app
      - ./data:/app/data
      - ./results:/app/results
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5001
      - CONFIG_PATH=/app/config.production.yaml
    command: python src/models/model_monitoring.py
