name: fraud_detection
channels:
  - apple
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=23.1.2
  - "libblas=*=*accelerate"  # Apple Accelerate framework optimization
  - pip:
    # Core ML and Data Processing
    - pyspark==3.3.2
    - tensorflow==2.13.0
    - tensorflow-metal==1.0.0  # Apple Metal GPU support
    - scikit-learn==1.3.0
    - pandas==2.0.3
    - numpy==1.24.3
    - pyarrow==12.0.0
    - fastparquet==2023.7.0
    - imbalanced-learn==0.11.0
    
    # Visualization
    - matplotlib==3.7.2
    - seaborn==0.12.2
    
    # Development and Notebooks
    - jupyter==1.0.0
    
    # MLOps and Experiment Tracking
    - mlflow==2.6.0
    - pyyaml==6.0.1
    
    # Production Dependencies
    - gunicorn==21.2.0
    - flask==2.3.3
    - redis==5.0.0
    - prometheus-client==0.17.1
    - prometheus-flask-exporter==0.22.4
    
    # Monitoring and Logging
    - wandb==0.15.8
    
    # Testing
    - pytest==7.4.0
    - pytest-cov==4.1.0
